#' Title: Function to get R2, Sy, and slope
#'
#' \code{get.rsquared} uses the linear modelling function \code{\link{lm}} to calculate the R2, the residual of the standard error (Sy),
#' and slope from a data set. These are all helpful in defining correlation and calculating limits of detection.
#' The end result is a list.
#'
#' @usage
#'x and y are strings with the respective column names.
#'
#' @param data A dataframe with the x and y values to be calculated.
#' @param x A string ("name") indicating the name of the column with the x axis value (independent variable)
#' @param y A string ("name") indicating the name of the column with the y axis value (dependent variable)
#'
#' @return A list is generated with the following components:
#' \item{R2 }{R2 of data set}
#' \item{b }{b-intercept of linear equation}
#' \item{slope }{Slope of the linear equation generated by lm}
#' \item{residuals }{Sy: The sd of the residuals}
#'
#' @examples
#' example_data <- data.frame(x = c(1, 2, 3), y = c(3, 67, 90))
#' get.rsquared(example_data, "x", "y")

# r squared function -------
#' @export
get.rsquared <- function(data, x, y){
  # Ensure x and y are character strings representing column names
  formula <- as.formula(paste(y, "~", x))
  # Linear regression model
  ml <- lm(formula, data = data)
  # print rsquared
  list(R2 = summary(ml)$r.squared,
       b = coef(ml)[[1]],
       slope = coef(ml)[[2]],
       residuals = summary(ml)$sigma)
}
